### ISSUE TITLE
Is it possible to get all the used packages from pubspec.yaml

### ISSUE THREAD

**Issue by aytunch** [VeryGoodOpenSource/pub_updater#13]
If the user does not want to write all the packages, can you create a method which returns all the used packages?

**Comment by felangel** [comment]
Hi @aytunch 👋 
Thanks for opening an issue!

The current intended usage is in cases where you maintain a CLI or developer tool and want to notify users when they are using an outdated version. Can you please provide a bit more context regarding your use-case?

**Comment by aytunch** [comment]
@felangel I might have misunderstood this packages use-case
When I saw that user needs to write the current pub package name and version manually, I thought reading the packages from the pubspec.yaml automatically and checking all of them would be easier.
So let's say I want to use this to keep all the packages used in a project up to date, I would want it to be automatic.
But as I said, I might have misunderstood the packages intent and I don't use CLI too often :)

**Comment by UsamaKarim** [comment]
If you use VSCode, there is a good extension that does this job. Download it here. https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens
