### ISSUE TITLE
New version with process v5?

### ISSUE THREAD

**Issue by GP4cK** [VeryGoodOpenSource/pub_updater#54]
Hello, I see [the PR that upgrades process to v5](https://github.com/VeryGoodOpenSource/pub_updater/pull/52) was merged a couple of weeks ago. Is there any plan to publish a new version?
Thanks in advance.

**Comment by renancaraujo** [comment]
Yep, we should have a new version relatively soon.

**Comment by GP4cK** [comment]
This is available in 0.4.0.
