### ISSUE TITLE
chore: Confirm Flutter 3.24.0 and Dart 3.5 Support

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/pub_updater#61]
**Description**

With the release of Flutter 3.24.0 and Dart 3.5 some things are breaking. Need to review the package and make any necessary fixes.

**Requirements**

- [ ] Package works correctly on Flutter 3.24.0 and Dart 3.5

**Comment by alestiago** [comment]
Tried running the example and it succeeded after changing the package name.

There are a few dependencies that could be tighten, not sure if we would like to update them, these are:

```txt
  http: ^1.0.0 -> ^1.2.2
  json_annotation: ^4.1.0 -> ^4.9.0
  process: ^5.0.0 -> ^5.0.2
  pub_semver: ^2.1.3 -> ^2.1.4
  build_runner: ^2.1.2 -> ^2.4.12
  json_serializable: ^6.5.3 -> ^6.8.0
  mocktail: ^1.0.0 -> ^1.0.4
  test: ^1.17.0 -> ^1.25.8
  very_good_analysis: >=5.1.0 <7.0.0 -> ^6.0.0
```

**Comment by alestiago** [comment]
Closing as completed, the latest version v0.5.0 has been now released.
